In [1]:
import numpy as np
import math
m_sqr_arr = np.array([[1, 2], [4, -1]]) 
print(m_sqr_arr)
m_sqr_mx = np.matrix([[ 2, -3], [-4, 1]]) 
print(m_sqr_mx)
c=m_sqr_arr.dot(m_sqr_mx)
print(c)
k=m_sqr_mx.dot(m_sqr_arr)
print(k)
result=c-k
print (result)


[[ 1  2]
 [ 4 -1]]
[[ 2 -3]
 [-4  1]]
[[ -6  -1]
 [ 12 -13]]
[[-10   7]
 [  0  -9]]
[[ 4 -8]
 [12 -4]]


In [2]:
import numpy as np
import math
m_sqr_arr = np.array([[-1, 2], [0, 1]]) 
print(m_sqr_arr)
c = m_sqr_arr.dot(m_sqr_arr)
print(c)


[[-1  2]
 [ 0  1]]
[[1 0]
 [0 1]]


In [3]:
m_sqr_arr = np.array([[3, 5], [6, -1]]) 
print(m_sqr_arr)
m_sqr_mx = np.matrix([[ 2, 1], [-3, 2]]) 
print(m_sqr_mx)
c=m_sqr_arr.dot(m_sqr_mx)
print(c)


[[ 3  5]
 [ 6 -1]]
[[ 2  1]
 [-3  2]]
[[-9 13]
 [15  4]]


In [4]:
a = np.matrix('2 3 4; 1 0 4; 7 8 9')
print(a)
a_det = np.linalg.det(a) 
print(format(a_det, '.9g'))


[[2 3 4]
 [1 0 4]
 [7 8 9]]
25


In [5]:
a = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3')
print(a)
a_det = np.linalg.det(a) 
print(format(a_det, '.9g'))


[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]
-160


In [6]:
A = np.matrix('1 2 -3; 0 1 2; 0 0 1')
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [7]:
A = np.matrix('1 2 3 4; 3 -1 2 5; 1 2 3 4; 1 3 4 5')
rank = np.linalg.matrix_rank(A)
print(rank)


2


In [8]:
A = np.matrix('1 -2 3; 4 2 -3; 3 -3 5')
B = np.matrix('-5; 0; -9')
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)


A= [[ 1 -2  3]
 [ 4  2 -3]
 [ 3 -3  5]]
B= [[-5]
 [ 0]
 [-9]]
[[ 0.2  0.2  0. ]
 [-5.8 -0.8  3. ]
 [-3.6 -0.6  2. ]]
X= [[-1.]
 [ 2.]
 [ 0.]]
