<a href="https://colab.research.google.com/github/yev34/CMP/blob/main/Patalashko_lab1_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) з числами, які є оберненими значеннями
простих чисел, починаючи з 2, та виведіть його значення.

In [1]:
import sympy as sp
primes = list(sp.primerange(2, 30))
inverse_primes = [1/p for p in primes]
inverse_primes


[0.5,
 0.3333333333333333,
 0.2,
 0.14285714285714285,
 0.09090909090909091,
 0.07692307692307693,
 0.058823529411764705,
 0.05263157894736842,
 0.043478260869565216,
 0.034482758620689655]

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратних коренів перших натуральних чисел.

In [2]:
import numpy as np

natural_numbers = np.arange(1, 10)

sqrt_numbers = np.sqrt(natural_numbers)

matrix = sqrt_numbers.reshape((3, 3))

print(matrix)


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -10 до
10 та знайдіть суму елементів кожного рядка.

In [6]:
import numpy as np

matrix = np.random.randint(-10, 11, size=(3, 3))

row_sums = np.sum(matrix, axis=1)

print("Matrix:\n", matrix)
print("Sum of each row:", row_sums)


Matrix:
 [[-10   2   3]
 [  0   4   1]
 [-10  -7  10]]
Sum of each row: [-5  5 -7]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -1.0
до 1.0 та виведіть його значення.

In [5]:
import numpy as np

array = np.random.uniform(-1.0, 1.0, (4, 4))

print(array)


[[-0.14759713  0.73429219 -0.40840142 -0.43228404]
 [ 0.13315211  0.19372631  0.99143286 -0.90874724]
 [-0.35055334 -0.05707728 -0.28265599 -0.54391465]
 [ 0.34970578 -0.91927847  0.05639879  0.32371393]]


Створіть два одновимірних масиви розміром 8, заповніть їх випадковими цілими
числами в діапазоні від 5 до 10 та виконайте на них поелементні операції додавання,
віднімання та множення

In [4]:
import numpy as np

array1 = np.random.randint(5, 11, 8)
array2 = np.random.randint(5, 11, 8)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [ 6  6  6  5 10 10  9  9]
Array 2: [10  9  8 10  9 10  8  6]
Addition: [16 15 14 15 19 20 17 15]
Subtraction: [-4 -3 -2 -5  1  0  1  3]
Multiplication: [ 60  54  48  50  90 100  72  54]


Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 15 та
знайдіть їх добуток.

In [3]:
import numpy as np

array1 = np.random.randint (1,15, size =(4,4))
array2 = np.random.randint (1,15, size =(4,4))

mult= array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Multiplication:", mult)

Array 1: [[ 3 11  4 14]
 [ 7  2  4 10]
 [14  3  9 14]
 [12  2  6  8]]
Array 2: [[ 7 14 11 14]
 [13  9  4  5]
 [ 1  4 13  4]
 [ 3  9 12  3]]
Multiplication: [[ 21 154  44 196]
 [ 91  18  16  50]
 [ 14  12 117  56]
 [ 36  18  72  24]]


Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 6 та перемножте їх між собою.

In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 7, (4, 2))

matrix2 = np.random.randint(1, 7, (2, 2))

result = np.dot(matrix1, matrix2)

print("Matrix 1 (4x2):")
print(matrix1)
print("\nMatrix 2 (2x2):")
print(matrix2)
print("\nResult of multiplication:")
print(result)


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть її обернену матрицю.

In [12]:
import numpy as np
matrix = np.random.randint(1, 11, (3, 3))

print("Original Matrix:")
print(matrix)

determinant = np.linalg.det(matrix)

inverse_matrix = np.linalg.inv(matrix)
print("\nInverse Matrix:")
print(inverse_matrix)


Original Matrix:
[[5 1 7]
 [1 4 7]
 [1 3 9]]

Inverse Matrix:
[[ 0.22727273  0.18181818 -0.31818182]
 [-0.03030303  0.57575758 -0.42424242]
 [-0.01515152 -0.21212121  0.28787879]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 100 та транспонуйте її.

In [13]:
import numpy as np

matrix = np.random.uniform(0, 100, (4, 4))

print("Original Matrix:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[69.39839434 85.81590783 69.46968612 41.38063251]
 [44.40469064 70.74354814 28.40426087 83.65835445]
 [27.47093305 64.17167856 87.8797443  15.54609893]
 [56.02721904 56.03334483 67.50484174 22.79361573]]

Transposed Matrix:
[[69.39839434 44.40469064 27.47093305 56.02721904]
 [85.81590783 70.74354814 64.17167856 56.03334483]
 [69.46968612 28.40426087 87.8797443  67.50484174]
 [41.38063251 83.65835445 15.54609893 22.79361573]]


Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [15]:
import numpy as np

matrix = np.random.uniform(0, 1, (3, 4))

vector = np.random.randint(1, 11, (4, 1))

print("Matrix (3x4):")
print(matrix)
print("\nVector (4x1):")
print(vector)

result = np.dot(matrix, vector)

print("\nResult of multiplication (3x1):")
print(result)


Matrix (3x4):
[[0.8772229  0.43991272 0.55849885 0.87372609]
 [0.48218973 0.94190693 0.88333356 0.25273965]
 [0.97362105 0.69628842 0.94818799 0.12149439]]

Vector (4x1):
[[8]
 [5]
 [8]
 [9]]

Result of multiplication (3x1):
[[21.54887245]
 [17.90837777]
 [19.94936388]]


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [16]:
import numpy as np

matrix = np.random.randint(1, 10, (2, 3))

vector = np.random.uniform(0, 1, (3, 1))

print("Matrix (3x4):")
print(matrix)
print("\nVector (4x1):")
print(vector)

result = np.dot(matrix, vector)

print("\nResult of multiplication (3x1):")
print(result)


Matrix (3x4):
[[7 4 3]
 [5 4 3]]

Vector (4x1):
[[0.53662904]
 [0.21637773]
 [0.61353166]]

Result of multiplication (3x1):
[[6.46250919]
 [5.38925111]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від -5 до 3 та знайдіть добуток всіх елементів другої матриці.

In [17]:
import numpy as np

array1 = np.random.randint(-5, 3, (2,2))
array2 = np.random.randint(-5, 3, (2,2))

mult = np.prod(array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Multiplication:", mult)

Array 1: [[ 1 -4]
 [ 2 -2]]
Array 2: [[-5 -4]
 [ 2  2]]
Multiplication: 80


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -1 до 5 та знайдіть добуток їх елементів.

In [19]:
import numpy as np

matrix1 = np.random.randint(-1, 5, (3, 3))

matrix2 = np.random.randint(-1, 5, (3, 3))

print("Matrix 1 (3x3):")
print(matrix1)
print("\nMatrix 2 (3x3):")
print(matrix2)

product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("\nProduct of all elements in Matrix 1:")
print(product_matrix1)
print("\nProduct of all elements in Matrix 2:")
print(product_matrix2)

Matrix 1 (3x3):
[[ 3  1  2]
 [-1  0  4]
 [ 3  3 -1]]

Matrix 2 (3x3):
[[ 1  4  3]
 [ 3 -1  1]
 [ 4  4  4]]

Product of all elements in Matrix 1:
0

Product of all elements in Matrix 2:
-2304


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть суму елементів на побічній діагоналі.

In [20]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))

print("Matrix (3x3):")
print(matrix)

n = matrix.shape[0]
secondary_diagonal_sum = np.sum([matrix[i, n - 1 - i] for i in range(n)])

print("\nSum of elements in the secondary diagonal:")
print(secondary_diagonal_sum)


Matrix (3x3):
[[6 2 5]
 [9 1 5]
 [1 3 7]]

Sum of elements in the secondary diagonal:
7


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє арифметичне
значення елементів кожного стовпця матриці.

In [21]:
import numpy as np

matrix = np.random.uniform(-2, 2, (3, 3))

print("Matrix (3x3):")
print(matrix)

column_means = np.mean(matrix, axis=0)

column_means_vector = column_means.reshape(-1, 1)

print("\nColumn means (as a column vector):")
print(column_means_vector)


Matrix (3x3):
[[ 1.84589461  1.51036299 -0.46458212]
 [-0.18574476  1.48037     1.25595796]
 [ 0.72380664  1.55381446  0.69406301]]

Column means (as a column vector):
[[0.79465217]
 [1.51484915]
 [0.49514628]]
